### ISSUE TITLE
Materia Compact Gtk theme causes error message

### ISSUE THREAD

**Issue by stuaxo** [Cybolic/vineyard#10]
Using this theme

https://github.com/nana-4/materia-theme

on a hidpi  theme I get the message at the end of this bug report

Image info:
/usr/share/themes/Materia-compact/gtk-2.0/assets/notebook-combo-ltr-entry-insensitive.png: PNG image data, 10 x 20, 8-bit grayscale, non-interlaced

I believe this is the same image
https://github.com/lirios/material-gtk-theme/blob/master/gtk-2.0/assets/notebook-combo-entry-ltr-entry-insensitive.png

```
** (vineyard-preferences:7053): WARNING **: Invalid borders specified for theme pixmap:
        /usr/share/themes/Materia-compact/gtk-2.0/assets/notebook-combo-ltr-entry-insensitive.png,
borders don't fit within the image
	It exists, adding.../usr/lib/wine
	It exists, adding.../usr/lib/i386-linux-gnu/wine/
	It exists, adding.../usr/lib/x86_64-linux-gnu/wine/

** (vineyard-preferences:7053): WARNING **: Invalid borders specified for theme pixmap:
        /usr/share/themes/Materia-compact/gtk-2.0/assets/notebook-combo-ltr-entry.png,
borders don't fit within the image
```

**Comment by Cybolic** [comment]
If I'm not mistaken, this is just an error in the theme, not Vineyard itself. Is it causing any errors?

**Comment by stuaxo** [comment]
Good question, I haven't used vineyard enough to know, Will close since for now and maybe reopen if I find it causing an issue.
