### ISSUE TITLE
Question about the licence used.

### ISSUE THREAD

**Issue by TomJansen** [Cybolic/vineyard#13]
Hello and thank you for this amazing project! It is sad to see that is isn't as popular as the other wine front-ends (yet)

I have a question about the licence used. In the program (tools>about>licence) it says that it is licensed under the GPLv2. But here on Github, under COPYING, it says it licensed under the GNU Library General Public License, version 2.0.

Thank you

**Comment by Cybolic** [comment]
Good question! Vineyard is licensed under a dual license as it's actually composed of two parts:

1. The Vineyard user tools
2. The python-wine library

Vineyard is licensed under GPLv2 (or later) and python-wine is licensed under LGPLv2 (or later) to allow it to be used with other Wine related projects that may include proprietary software (such as an installer for a Wine wrapped program).

**Comment by TomJansen** [comment]
Thank you, this clears it all up.
