### ISSUE TITLE
vineyard-preferences does not work properly

### ISSUE THREAD

**Issue by sputniktr02** [Cybolic/vineyard#4]
I cannot create new prefixes and also most of the settings sometimes greyed out sometimes not persistent when changed. I played around while terminal is open and here is the output;

`:~$ vineyard-preferences
/usr/lib/python2.7/dist-packages/vineyard/common.py:111: GtkWarning: Unable to locate theme engine in module_path: "adwaita",
  icon_theme_default = gtk.icon_theme_get_default()

** (vineyard-preferences:2188): WARNING **: Invalid borders specified for theme pixmap:
        /usr/share/themes/Breeze/gtk-2.0/../assets/line-h.png,
borders don't fit within the image
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/vineyard/async.py", line 85, in _callback
    callback(*args)
  File "/usr/bin/vineyard-preferences", line 892, in __update
    self.__update_configurations(select_configuration = self.__creating_prefix_name)
  File "/usr/bin/vineyard-preferences", line 290, in __update_configurations
    select_configuration
  File "/usr/lib/python2.7/dist-packages/wine/prefixes.py", line 457, in get_metadata_from_name_or_prefix
    raise StandardError, "Couldn't find prefix"
StandardError: Couldn't find prefix
Error occured
There was an error running the threaded function: coercing to Unicode: need string or buffer, NoneType found
/usr/lib/python2.7/dist-packages/vineyard/async.py:64
/usr/bin/vineyard-preferences:483
/usr/lib/python2.7/dist-packages/wine/version.py:116
/usr/lib/python2.7/dist-packages/wine/version.py:164
/usr/lib/python2.7/dist-packages/wine/registry.py:349
/usr/lib/python2.7/dist-packages/wine/registry.py:92
/usr/lib/python2.7/dist-packages/wine/registry.py:26
<type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found
None
Error occured
There was an error running the threaded function: coercing to Unicode: need string or buffer, NoneType found
/usr/lib/python2.7/dist-packages/vineyard/async.py:64
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:90
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:172
/usr/lib/python2.7/dist-packages/wine/windows.py:18
/usr/lib/python2.7/dist-packages/wine/registry.py:268
/usr/lib/python2.7/dist-packages/wine/registry.py:26
<type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found
None
Error occured
There was an error running the threaded function: coercing to Unicode: need string or buffer, NoneType found        
/usr/lib/python2.7/dist-packages/vineyard/async.py:64                                                               
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:90                                                      
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:172                                                     
/usr/lib/python2.7/dist-packages/wine/windows.py:38                                                                 
/usr/lib/python2.7/dist-packages/wine/registry.py:268                                                               
/usr/lib/python2.7/dist-packages/wine/registry.py:26                                                                
<type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found                           
None                                                                                                                
Error occured                                                                                                       
There was an error running the threaded function: coercing to Unicode: need string or buffer, NoneType found        
/usr/lib/python2.7/dist-packages/vineyard/async.py:64
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:90
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:172
/usr/lib/python2.7/dist-packages/wine/graphics.py:88
/usr/lib/python2.7/dist-packages/wine/registry.py:268
/usr/lib/python2.7/dist-packages/wine/registry.py:26
<type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found
None
Error occured
There was an error running the threaded function: coercing to Unicode: need string or buffer, NoneType found
/usr/lib/python2.7/dist-packages/vineyard/async.py:64
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:90
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:172
/usr/lib/python2.7/dist-packages/wine/appearance.py:235
/usr/lib/python2.7/dist-packages/wine/appearance.py:219
/usr/lib/python2.7/dist-packages/wine/registry.py:268
/usr/lib/python2.7/dist-packages/wine/registry.py:26
<type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found
None
Error occured
There was an error running the threaded function: coercing to Unicode: need string or buffer, NoneType found
/usr/lib/python2.7/dist-packages/vineyard/async.py:64
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:90
/usr/lib/python2.7/dist-packages/vineyard/widgets/virtual_desktop.py:93
/usr/lib/python2.7/dist-packages/wine/desktop.py:28
/usr/lib/python2.7/dist-packages/wine/registry.py:268
/usr/lib/python2.7/dist-packages/wine/registry.py:26
<type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found
None
Error occured
There was an error running the threaded function: coercing to Unicode: need string or buffer, NoneType found
/usr/lib/python2.7/dist-packages/vineyard/async.py:64
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:90
/usr/lib/python2.7/dist-packages/vineyard/widgets/themes.py:125
/usr/lib/python2.7/dist-packages/wine/appearance.py:130
/usr/lib/python2.7/dist-packages/wine/registry.py:268
/usr/lib/python2.7/dist-packages/wine/registry.py:26
<type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found
None
Error occured
There was an error running the threaded function: coercing to Unicode: need string or buffer, NoneType found
/usr/lib/python2.7/dist-packages/vineyard/async.py:64
/usr/lib/python2.7/dist-packages/vineyard/widgets/widget.py:90
/usr/lib/python2.7/dist-packages/vineyard/widgets/drives.py:348
/usr/lib/python2.7/dist-packages/wine/drives.py:209
/usr/lib/python2.7/dist-packages/wine/registry.py:268
/usr/lib/python2.7/dist-packages/wine/registry.py:26
<type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found` 

Hope that helps.

**Comment by Cybolic** [comment]
Thanks for reporting it! :D
f38a8850b638d02c07ef0fdeaefca6c1c833ea91 should fix the last bunch of errors at least. Could you also send me a listing of your main Wine prefix (`~/.wine`) as well as `~/.local/share/wineprefixes`? That should give me a hint about what's going on with the prefix error.
(`ls -ld ~/.wine/* ~/.local/share/wineprefixes/*`)

**Comment by sputniktr02** [comment]
It seems I don't have such directory. I am using wine-staging by the way.

```
~$ ls -ld ~/.wine/* ~/.local/share/wineprefixes/*
ls: cannot access '/home/user/.local/share/wineprefixes/*': No such file or directory
drwxrwxr-x 2 user user    4096 Ağu 24 14:56 /home/user/.wine/dosdevices
drwxrwxr-x 6 user user    4096 Ağu 12 16:52 /home/user/.wine/drive_c
-rw-rw-r-- 1 user user 2830070 Ağu 25 11:14 /home/user/.wine/system.reg
-rw-rw-r-- 1 user user    3242 Haz 14 19:29 /home/user/.wine/userdef.reg
-rw-rw-r-- 1 user user   98974 Ağu 25 11:14 /home/user/.wine/user.reg
drwxrwxr-x 3 user user    4096 Ağu 24 14:56 /home/user/.wine/vineyard
```

**Comment by Cybolic** [comment]
Could you see if the latest update fixed this?

**Comment by sputniktr02** [comment]
Yes. I can now add new prefixes. Thanks.
