### ISSUE TITLE
vineyard on Ubuntu 17.10

### ISSUE THREAD

**Issue by Arpan-Arora** [Cybolic/vineyard#6]
sudo apt update -y
Ign:1 http://ppa.launchpad.net/cybolic/ppa/ubuntu artful InRelease
Get:2 http://security.ubuntu.com/ubuntu artful-security InRelease [76.7 kB]
Hit:3 http://in.archive.ubuntu.com/ubuntu artful InRelease
Get:4 http://in.archive.ubuntu.com/ubuntu artful-updates InRelease [78.6 kB]
Err:5 http://ppa.launchpad.net/cybolic/ppa/ubuntu artful Release
  404  Not Found
Hit:6 http://in.archive.ubuntu.com/ubuntu artful-backports InRelease
Hit:7 http://cz.archive.ubuntu.com/ubuntu xenial InRelease
Reading package lists... Done                      
_E: The repository 'http://ppa.launchpad.net/cybolic/ppa/ubuntu artful Release' does not have a Release file._
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by stuaxo** [comment]
Just came here as I noticed the same thing - Artful not listed on the PPA so I guess it needs to be added.
Kind of surprised in years of using wine I only just found vinyard - it looks like something wine should come with anyway.

**Comment by Cybolic** [comment]
I've added Zenial, Artful and Bionic as build targets now. Launchpad should have new packages up soon :)

**Comment by Cybolic** [comment]
New packages are now up.
